MvcOnlineTicariOtomasyon/Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class FaturaController : Controller
    {
        // GET: Fatura
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Faturalars.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult FaturaEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FaturaEkle(Faturalar f)
        {
            c.Faturalars.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult FaturaGetir(int id)
        {
            var fatura = c.Faturalars.Find(id);
            return View("FaturaGetir", fatura);
        }

        public ActionResult FaturaGuncelle(Faturalar f)
        {
            var fatura = c.Faturalars.Find(f.Faturaid);
            fatura.FaturaSeriNo = f.FaturaSeriNo;
            fatura.FaturaSiraNo = f.FaturaSiraNo;
            fatura.Saat = f.Saat;
            fatura.Tarih = f.Tarih;
            fatura.TeslimAlan = f.TeslimAlan;
            fatura.TeslimEden = f.TeslimEden;
            fatura.VergiDairesi = f.VergiDairesi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult FaturaDetay(int id)
        {
            var degerler = c.FaturaKalems.Where(x => x.Faturaid == id).ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniKalem()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniKalem(FaturaKalem p)
        {
            c.FaturaKalems.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Fatura/FaturaDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<FaturaKalem>
@{
    ViewBag.Title = "FaturaDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Fatura Kalemleri Sayfası</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"></li>
</ol>
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Açıklama</th>
        <th>Miktar</th>
        <th>Birim Fiyat</th>
        <th>Tutar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td> @x.FaturaKalemid </td>
            <td> @x.Aciklama </td>
            <td> @x.Miktar </td>
            <td> @x.BirimFiyat </td>
            <td> @x.Tutar </td>
        </tr>
    }
</table>

<a href="/Fatura/YeniKalem/" class="btn btn-default" style="background-color:darksalmon">Yeni Kalem Girişi</a>

MvcOnlineTicariOtomasyon/Views/Fatura/FaturaEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Faturalar
    @{
        ViewBag.Title = "FaturaEkle";
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }

    <br />
    <h2>Yeni Fatura Sayfası</h2>
    <br />
    <form class="form-group" method="post">

        @Html.LabelFor(x => x.FaturaSeriNo)
        @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.FaturaSiraNo)
        @Html.TextBoxFor(x => x.FaturaSiraNo, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Tarih)
        @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.VergiDairesi)
        @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Saat)
        @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.TeslimEden)
        @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.TeslimAlan)
        @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Kaydet</button>
    </form>

MvcOnlineTicariOtomasyon/Views/Fatura/FaturaGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Faturalar
    @{
        ViewBag.Title = "FaturaGetir";
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }

    <br />
    <h2>Fatura Güncelleme Sayfası</h2>
    <br />

    @using (Html.BeginForm("FaturaGuncelle", "Fatura", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.Faturaid)
        @Html.LabelFor(x => x.FaturaSeriNo)
        @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.FaturaSiraNo)
        @Html.TextBoxFor(x => x.FaturaSiraNo, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.VergiDairesi)
        @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Tarih)
        @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Saat)
        @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.TeslimEden)
        @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.TeslimAlan)
        @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">Güncelle</button>
    }

MvcOnlineTicariOtomasyon/Views/Fatura/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Faturalar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Fatura Sayfası</h2>

<table class="table table-bordered" style="margin-top:20px">

    <tr>
        <th>ID</th>
        <th>Seri No</th>
        <th>Sıra No</th>
        <th>Vergi Dairesi</th>
        <th>Tarih</th>
        <th>Saat</th>
        <th>Teslim Eden</th>
        <th>Teslim Alan</th>
        <th>Toplam Tutar</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var k in Model)
    {
    <tr>
        <td>@k.Faturaid</td>
        <td>@k.FaturaSeriNo</td>
        <td>@k.FaturaSiraNo</td>
        <td>@k.VergiDairesi</td>
        <td>@k.Tarih</td>
        <td>@k.Saat</td>
        <td>@k.TeslimEden</td>
        <td>@k.TeslimAlan</td>
        <td>@k.Toplam</td>
        <td><a href="/Fatura/FaturaGetir/@k.Faturaid" class="btn btn-warning">Güncelle</a></td>
        <td>
            <a href="/Fatura/FaturaDetay/@k.Faturaid"
               class="btn btn-default" style="background-color:coral">Detay</a>
        </td>

    </tr>
    }

</table>
<a href="/Fatura/FaturaEkle" class="btn btn-info">Yeni Fatura Girişi</a>

MvcOnlineTicariOtomasyon/Views/Fatura/YeniKalem.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.FaturaKalem
    @{
        ViewBag.Title = "YeniKalem";
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }

    <br />
    <h2>Yeni Kalem Girişi</h2>
    <br />
    <form class="form-group" method="post">

        @Html.LabelFor(x => x.Aciklama)
        @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Miktar)
        @Html.TextBoxFor(x => x.Miktar, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.BirimFiyat)
        @Html.TextBoxFor(x => x.BirimFiyat, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Tutar)
        @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Faturaid)
        @Html.TextBoxFor(x => x.Faturaid, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Kaydet</button>
    </form>